# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('middle', models.CharField(blank=True, max_length=100)),
                ('last', models.CharField(max_length=100)),
            ],
        ),
    ]
